(deftheme vanquish
  "Created 2016-10-25.")

(custom-theme-set-faces
 'vanquish
 '(default ((t (:inherit nil :stipple nil :background "black" :foreground "cyan" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "unknown" :family "Neuropolitical"))))
 '(cursor ((t (:background "cyan"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "medium blue"))))
 '(highlight ((t (:background "yellow" :foreground "black"))))
 '(region ((t (:background "cyan" :foreground "black"))))
 '(shadow ((t (:foreground "white"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:background "yellow")) (((class color) (min-colors 16) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 8)) (:foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "dark orange"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "gold"))))
 '(font-lock-comment-face ((t (:foreground "yellow" :slant oblique))))
 '(font-lock-constant-face ((t (:foreground "navy" :weight bold))))
 '(font-lock-doc-face ((t (:foreground "yellow" :slant oblique))))
 '(font-lock-function-name-face ((t (:foreground "dark slate blue" :weight bold :height 1.1))))
 '(font-lock-keyword-face ((t (:foreground "white"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "green" :slant italic))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold))))
 '(font-lock-string-face ((t (:foreground "white"))))
 '(font-lock-type-face ((t (:foreground "SteelBlue1"))))
 '(font-lock-variable-name-face ((t (:foreground "gray"))))
 '(font-lock-warning-face ((t (:foreground "red" :weight bold))))
 '(button ((t (:background "grey" :foreground "white" :box (:line-width 2 :color "grey" :style released-button) :underline t :weight bold))))
 '(link ((t (:foreground "dark blue" :underline t))))
 '(link-visited ((t (:foreground "dark cyan" :underline t))))
 '(fringe ((t (:background "black" :foreground "cyan"))))
 '(header-line ((t (:background "grey20" :foreground "cyan" :box (:line-width -1 :color "grey20" :style released-button) :height 0.9))))
 '(tooltip ((t (:foreground "black" :background "lightyellow"))))
 '(mode-line ((t (:background "black" :foreground "cyan" :box nil :height 0.9))))
 '(mode-line-buffer-id ((t (:background "black" :foreground "yellow" :weight bold :height 0.9))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:background "black" :foreground "dark gray" :box (:line-width 2 :color "grey75" :style released-button) :weight light :height 0.9))))
 '(isearch ((t (:background "yellow" :foreground "black"))))
 '(isearch-fail ((t (:background "red" :foreground "black"))))
 '(lazy-highlight ((t (:background "paleturquoise4"))))
 '(match ((t (:background "white" :foreground "black"))))
 '(next-error ((t (:background "black" :foreground "red"))))
 '(query-replace ((t (:background "black" :foreground "yellow")))))

(provide-theme 'vanquish)
